version: '3.1'
services:

  mariadb:
    build: ./MariaDB/
    image: annafiona/mariadb
    container_name: maria

    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ADMIN_USER: '${MYSQL_ADMIN_USER}'
      MYSQL_ADMIN_PASSWORD: '${MYSQL_ADMIN_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception


  wordpress:
    depends_on:
      - mariadb

    build: ./WordPress/
    image: annafiona/wordpress
    container_name: wordpress

    restart: always
    ports:
      - 9000:9000 #?
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_ADMIN_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_ADMIN_PASSWORD}'
    volumes:
      - wp_website_files:/var/www/html
    networks: 
      - inception


  nginx:
    depends_on:
      - wordpress
    build: ./NGINX/
    image: annafiona/nginx
    container_name: nginx

    restart: always
    ports:
      - 443:443
      - 80:80
    env_file: .env
    environment: #needed?
      MYSQL_ADMIN_PASSWORD: '${MYSQL_ADMIN_PASSWORD}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ADMIN_USER: '${MYSQL_ADMIN_USER}'
    volumes:
      - wp_website_files:/var/www/html
    networks:
      - inception

networks: #allowed?
  inception:
    driver: bridge

volumes:
  wp_website_files:  #needs to be in a folder (subject!!!) in host machine (vm)?!
  wp_db: #mariadb    #needs to be in a folder (subject!!!) in host machine (vm)?!
