services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: maria

    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ADMIN_USER: '${MYSQL_ADMIN_USER}'
      MYSQL_USER: '${MYSQL_USER}'
    secrets:
      - admin_pw
      - user_pw
    volumes:
      - wp_db:/var/www/html
    networks:
      - inception


  wordpress:
    depends_on:
      - mariadb

    build: ./requirements/wordpress/
    container_name: wordpress

    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE_HOST: '${MYSQL_DATABASE_HOST}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ADMIN_USER: '${MYSQL_ADMIN_USER}'
    secrets:
      - admin_pw
      - user_pw
    volumes:
      - wp_website_files:/var/www/html
    networks: 
      - inception


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx

    restart: always
    ports:
      - 443:443
    volumes:
      - wp_website_files:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes: 
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aplank/data/
  wp_website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aplank/data

secrets:
  admin_pw:
    file: ./../secrets/admin_pw.txt
  user_pw:
    file: ./../secrets/user_pw.txt