version: '3.1'
services:
  wordpress:
    depends_on:
      - mariadb

    build: ./WordPress/
    image: annafiona/wordpress
    container_name: wordpress

    #image: wordpress:6.2.2-apache

    restart: always #?
    ports:
      - 8080:80 #?
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - wp_website_files:/var/www/html
    networks: 
      - inception


# NGINX:

  mariadb:

    build: ./MariaDB/
    image: annafiona/mariadb
    container_name: maria

    #image: mariadb

    restart: always #?
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'

    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception


###############from tutorial
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - inception
#################

networks: #allowed?
  inception:
    driver: bridge

volumes:
  wp_website_files:  #needs to be in a folder (subject!!!) in host machine (vm)?!
  wp_db: #mariadb    #needs to be in a folder (subject!!!) in host machine (vm)?!
