services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - wp_db:/var/www/html
    networks:
      - inception


  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wp_website_files:/var/www/html
    networks: 
      - inception


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wp_website_files:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes: 
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aplank/data/
  wp_website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aplank/data