services:

  mariadb:
    build: ./requirements/mariadb/
    image: annafiona/mariadb
    container_name: maria

    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ADMIN_USER: '${MYSQL_ADMIN_USER}'
      MYSQL_USER: '${MYSQL_USER}'
    secrets:
      - admin_pw
      - user_pw
    volumes:
      - type: bind
        source: /home/aplank/data/wp_db
        target: /var/www/html
    networks:
      - inception


  wordpress:
    depends_on:
      - mariadb

    build: ./requirements/wordpress/
    image: annafiona/wordpress
    container_name: wordpress

    restart: always
    ports:
      - 9000:9000
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_ADMIN_USER}'
    secrets:
      - admin_pw
      - user_pw
    volumes:
      - type: bind
        source: /home/aplank/data/wp_website_files
        target: /var/www/html
    networks: 
      - inception


  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    image: annafiona/nginx
    container_name: nginx

    restart: always
    ports:
      - 443:443
    volumes:
      - type: bind
        source: /home/aplank/data/wp_website_files
        target: /var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

secrets:
  admin_pw:
    file: ./../secrets/admin_pw.txt
  user_pw:
    file: ./../secrets/user_pw.txt